name: FishFriends
options:
  deploymentTarget:
    iOS: "16.0"
targets:
  FishFriends:
    type: application
    platform: iOS
    sources:
      - path: Sources
      - path: Resources
      - path: ../web
        type: folder
        buildPhase: resources
    info:
      path: Info.plist
      properties:
        CFBundleDisplayName: Fish Friends
        UILaunchScreen: {}
        UIRequiresFullScreen: true
        UIStatusBarHidden: true
        UIViewControllerBasedStatusBarAppearance: false
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.taylorernst.fishfriends
        TARGETED_DEVICE_FAMILY: "2"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic
        SWIFT_VERSION: "5.0"
